name: Auto PR to Main

on:
  push:
    branches:
      - 'Feature_*'
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch to create a PR from'
        required: true
        default: 'Feature_Gokul'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print source branch for debug
        run: echo "Feature_Gokul"

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.event.inputs.source_branch }}
          destination_branch: "main"
          pr_title: "Auto PR from `${{ github.event.inputs.source_branch }}` to `main`"
          pr_body: "This is an automated PR triggered by a push or manual dispatch from `${{ github.event.inputs.source_branch }}`"
          github_token: ${{ secrets.GITHUB_TOKEN }}
