name: Auto PR to Main

on:
  push:
    branches:
      - 'Feature_*'
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch to create a PR from'
        required: true
        default: 'Feature_Gokul'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"title":"Auto PR from ${{ github.event.inputs.source_branch }} to main","head":"${{ github.event.inputs.source_branch }}","base":"main","body":"This is an automated PR triggered by a push or manual dispatch."}' \
            https://api.github.com/repos/${{ github.repository }}/pulls
