name: Auto PR to Main

on:
  push:
    branches-ignore:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Create Pull Request to main
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        pr_title: "Auto PR: ${{ github.ref_name }} → main"
        pr_body: "This is an automated PR from `${{ github.ref_name }}`"
        github_token: ${{ secrets.GITHUB_TOKEN }}
