name: Auto PR to Main

on:
  push:
    branches:
      - Feature_Gokul

  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch to create a PR from'
        required: false
        default: 'Feature_Gokul'

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/cli-action@v3

      - name: Determine source branch
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "branch=${{ github.event.inputs.source_branch }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request using GitHub CLI
        run: |
          gh pr create \
            --base main \
            --head ${{ steps.vars.outputs.branch }} \
            --title "Auto PR from ${{ steps.vars.outputs.branch }}" \
            --body "PR created automatically via workflow (${{ github.event_name }})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
